
import "./globals.css";
import Wrap from "./wrap";
import { Providers } from "./providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body >
        <Providers>
          <Wrap>{children}</Wrap>
        </Providers>
      </body>
    </html>
  );
}
